### ISSUE TITLE
Runtime error when running Business Logic CLI

### ISSUE THREAD

**Issue by seamug** [KinveyApps/Who-s-At-Glue#2]
Hi I tried executing the latest version of Business Logic CLI and encountered a runtime error. Pleae see attached. Can you kindly advise? I'm running Window OS 8.1 pro.
![runtime](https://cloud.githubusercontent.com/assets/4831208/6868603/ddb93510-d4c7-11e4-96d3-5aaaaf107b73.png)

**Comment by EchoAbstract** [comment]
@seamug I tried to reproduce the issue using Windows 8.1 and Window 10, but I was unable to get the same error.  What's the exact command you were running when you saw this error?

**Comment by seamug** [comment]
Hi Brian

I was running the only .exe file available 

Apologies for the brevity of this message

**Comment by EchoAbstract** [comment]
Thanks, did you run this via the Command Prompt or by double clicking on the exe?

**Comment by seamug** [comment]
Double-clicked. 

Apologies for the brevity of this message

**Comment by EchoAbstract** [comment]
Ah, the tool is meant to be used via the command line.  Take a look at the Readme.md file that's in the download and see if that helps with the right steps to get you up and running.

**Comment by seamug** [comment]
I see.. ok silly me .. Thanks!!
